### ISSUE TITLE
Coding style should be defined and checkable

### ISSUE THREAD

**Issue by jschwartzentruber** [MozillaSecurity/lithium#15]
Pylint gives a lot of warnings:

    +-----------+-------+
    |type       |number |
    +===========+=======+
    |convention |396    |
    +-----------+-------+
    |refactor   |10     |
    +-----------+-------+
    |warning    |40     |
    +-----------+-------+
    |error      |1      |
    +-----------+-------+
    
    Messages
    --------
    
    +------------------------------+------------+
    |message id                    |occurrences |
    +==============================+============+
    |invalid-name                  |316         |
    +------------------------------+------------+
    |bad-whitespace                |40          |
    +------------------------------+------------+
    |global-variable-not-assigned  |24          |
    +------------------------------+------------+
    |missing-docstring             |22          |
    +------------------------------+------------+
    |line-too-long                 |12          |
    +------------------------------+------------+
    |global-statement              |7           |
    +------------------------------+------------+
    |unused-variable               |5           |
    +------------------------------+------------+
    |too-many-locals               |4           |
    +------------------------------+------------+
    |too-many-statements           |3           |
    +------------------------------+------------+
    |too-many-branches             |3           |
    +------------------------------+------------+
    |superfluous-parens            |2           |
    +------------------------------+------------+
    |anomalous-backslash-in-string |2           |
    +------------------------------+------------+
    |wrong-import-position         |1           |
    +------------------------------+------------+
    |using-constant-test           |1           |
    +------------------------------+------------+
    |unneeded-not                  |1           |
    +------------------------------+------------+
    |trailing-whitespace           |1           |
    +------------------------------+------------+
    |too-many-lines                |1           |
    +------------------------------+------------+
    |redefined-builtin             |1           |
    +------------------------------+------------+
    |import-error                  |1           |
    +------------------------------+------------+
    
    Global evaluation
    -----------------
    Your code has been rated at 3.91/10 (previous run: 3.91/10, +0.00)

We should define a desired coding style for Lithium in a pylintrc (or alternative) and fix all violations, adding exceptions where needed. The same config should likely be used in other funfuzz based projects (jsfunfuzz/autobisect/DOMFuzz).

**Comment by jschwartzentruber** [comment]
To start this off, I'd suggest we move to [PEP-8](https://www.python.org/dev/peps/pep-0008/) style identifiers. (local_name vs localName for functions and variables)

**Comment by nth10sd** [comment]
This has been completed via several PRs, such as #22, #23, #24 and most recently #35.

All necessary suppressions are present in the repository and no longer assumes any presence of default pylintrc configurations on anybody's local machine.
