### ISSUE TITLE
No progress after character reduction

### ISSUE THREAD

**Issue by kamikazejunk** [MozillaSecurity/lithium#20]
After I hit character reduction on lithium, there is no progress...:(

Tested on Ubuntu 16.04

After this message was displayed, nothing happened(waited for a hour)... line reduction was succeeded, so I assume my install is fine. 

------------------------------------------------

Running character reduction...

/home/kaze/lithium/lithium/lithium.py --char /home/kaze/funfuzz/js/jsInteresting.py --minlevel=5 --timeout=20 mozilla-central shell-cache/js-64-dm-linux-cc65f9233e5b/js-64-dm-linux-cc65f9233e5b --fuzzing-safe --non-writable-jitcode --gc-zeal=8 --no-sse3 --no-baseline --ion-offthread-compile=off --ion-eager --ion-edgecase-analysis=off --ion-limit-script-size=off wtmp2/w16-reduced.js
Preparing to run Lithium, log file wtmp2/w16-5-lines-lith-out.txt
/usr/bin/python -u /home/kaze/funfuzz/util/../../lithium/lithium/lithium.py --tempdir=wtmp2/w16-5-lines-lith-tmp --char /home/kaze/funfuzz/js/jsInteresting.py --minlevel=5 --timeout=20 mozilla-central shell-cache/js-64-dm-linux-cc65f9233e5b/js-64-dm-linux-cc65f9233e5b --fuzzing-safe --non-writable-jitcode --gc-zeal=8 --no-sse3 --no-baseline --ion-offthread-compile=off --ion-eager --ion-edgecase-analysis=off --ion-limit-script-size=off wtmp2/w16-reduced.js

---------------------------------------------------

My temp folder was getting bigger and bigger... I think lithium is looping forever

This is my log file. Am I missing something?

[w16-5-lines-lith-out.txt](https://github.com/MozillaSecurity/lithium/files/1018012/w16-5-lines-lith-out.txt)

**Comment by nth10sd** [comment]
It still hasn't finished yet. The bottom of your log file shows:
```
Removing a chunk of size 1 starting at 152 of 1223 was a successful reduction :)
```
and then it was cut out by a KeyboardInterrupt, which I presume to be a Ctrl-C to cancel the command. I'd say let it run a little longer.

**Comment by nth10sd** [comment]
Moreover we ignore the unhandlable oom assertion messages, so I'm not sure if this testcase is particularly interesting.

**Comment by kamikazejunk** [comment]
Is there a way to skip this assertion? Everytime I hit this assertion, I need to wait for long time...:(

**Comment by nth10sd** [comment]
If you have a local FuzzManager instance, you can create a bucket for this type of assertion that the harness will then ignore for future runs. Same goes for other bugs.

**Comment by kamikazejunk** [comment]
Do I need to configure FuzzManager? or will lithium ignore the same assertion without configuration?

 I looked for a documentation, but I can't find how to skip a bug...

**Comment by nth10sd** [comment]
FuzzManager is located in [this repo](https://github.com/mozillasecurity/fuzzmanager) with setup instructions. You need to create a bucket to "skip" the bug, as funfuzz will check if a bucket of your signature is present before reporting to your instance of FuzzManager.

**Comment by kamikazejunk** [comment]
In order to skip the bug, is this setting correct?

------------------------------------------------------------------------------------------------------------

1. Go to http://ip-address/crashmanager/signatures/new/?crashid=[crash id]

2. Check "Mark this bucket as a frequent bucket" and "Reassign matching crashes" 

3. Save

**Comment by nth10sd** [comment]
If the local cache of signatures that FuzzManager creates, contains your required signature (via your bucket creation), the assertion will be ignored.

Anyway this is now beyond the scope of Lithium. The repo now contains much better tests (thanks @jschwartzentruber!), so please continue to file bugs if Lithium does not work properly for you.
