### ISSUE TITLE
Consider renaming some "lithium" names, e.g. of the subdirectory/file itself

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/lithium#32]
We use lots of the `lithium` name everywhere. It is used at least in:

* GitHub repo (Python package) name
* **Subdirectory name, adjacent to `interestingness`**
* The python filename `lithium.py` itself
* `Lithium` class object
  * Easier to differentiate due to capitalisation
* `lithium` logger in `lithium.py`
  * Easier to differentiate, but we could call it `lithLog` or something to make grepping for the word `lithium` less painful to scroll through

This made issues with the import system (e.g. PR #28) extremely hard to debug, due to confusion over whether a `lithium` word is a package/top-level file/module/directory. Even if they were all different, it would already have been complex due to Python packaging being hard to get right.

I would like to at least consider renaming the `lithium` subdirectory to `core`, and probably `lithium.py` to `lithreduce.py` or `lithreducer.py` as well. We might as well do this around the time we need to update our other repos to support #28 anyway, due to the need to move away from running lithium python files directly, instead importing lithium and running it as a module in funfuzz, for example.

@jschwartzentruber, thoughts?

**Comment by jschwartzentruber** [comment]
How about:

    lithium/lithium.py ➡️ core.py
    lithium/tests.py ➡️ tests.py
    lithium/doc/ ➡️ doc/
    lithium/examples/ ➡️ doc/examples/

I don't think we should rename the logger, since `lithium` exactly describes what we're logging from. I'm also not sure what you mean about grepping; the logger name is only used once to create the logger.

Note that changing the layout breaks usage as a script (calling `lithium.py` or `python lithium.py` directly). I think we should deprecate that entirely. We should encourage installing lithium as a module with pip or setup.py, and then use the [setuptools entry point](https://github.com/MozillaSecurity/lithium/blob/master/setup.py#L16) (`lithium`).

**Comment by nth10sd** [comment]
> I'm also not sure what you mean about grepping; the logger name is only used once to create the logger.

You're right, I got confused with the word in the actual messages.

I'm ok with moving doc/ and examples/ to top-level, do you think product_divides should be moved too?

Re: moving `lithium/lithium.py` and `lithium/tests.py` to top-level, I read somewhere that it's best for the main code to be in a subdirectory, sort-of a best practice kind-of thing, especially since we don't have to mess with imports/subdirs again (once I get them right in #28) should we need them in the future. How about:

```
lithium/lithium.py -> core/reducer.py (or some other name)
lithium/tests.py -> testing/tests.py or core/testing/tests.py
```

> Note that changing the layout breaks usage as a script (calling lithium.py or python lithium.py directly). I think we should deprecate that entirely. We should encourage installing lithium as a module with pip or setup.py, and then use the setuptools entry point (lithium).

I totally agree. That's why this should be done in the PR #28 as well, since it needs Lithium users to rework their repositories.

**Comment by nth10sd** [comment]
> I read somewhere that it's best for the main code to be in a subdirectory, sort-of a best practice kind-of thing

For reference, [pylint](https://github.com/PyCQA/pylint), [flake8](https://github.com/PyCQA/flake8), [boto](https://github.com/boto/boto), [requests](https://github.com/requests/requests) all only have setup.py Python file in their top-level directory, i.e. do not have their main code there.

**Comment by jschwartzentruber** [comment]
> I read somewhere that it's best for the main code to be in a subdirectory, sort-of a best practice kind-of thing

I found a concrete reason for packaging code in a subdirectory like 'src': https://github.com/pypa/setuptools/issues/230

This is making it impossible to use `setup.py develop` in [fuzzfetch](https://github.com/MozillaSecurity/fuzzfetch)

**Comment by nth10sd** [comment]
We agreed to end up with:

    lithium/lithium.py ➡️ core/reducer.py
    lithium/test_lithium.py ➡️ core/tests/test_lithium.py
    lithium/doc/ ➡️ doc/
    lithium/examples/ ➡️ doc/examples/

We will likely first cut a 0.1 pre-release before the renaming of directories.

**Comment by jschwartzentruber** [comment]
Based on the experience I had in one of our private repos (since this discussion) trying to get setup.py to work properly with both `pip install` and `pip install -e` .. I think we may need to do something more like this:

    lithium/lithium.py ➡️ lithium/core.py (or reducer.py)
    lithium/test_lithium.py ➡️ lithium/tests/test_lithium.py
    interestingness/ ➡️ lithium/interestingness/projects
    lithium/doc/ ➡️ doc/
    lithium/examples/ ➡️ doc/examples/
    __init__.py ➡️ 🗑 
    __main__.py ➡️ lithium/__main__.py

If you can make `core/` work, I'm all for it... but I couldn't :(

**Comment by nth10sd** [comment]
Oh, I think I might be able to get `core/` to work, just need to keep poking. Can you post all the rest of the commands that need to work? I can think of:

```
python setup.py develop
python setup.py sdist
python setup.py bdist
```

in addition to the ones you mentioned.

**Comment by jschwartzentruber** [comment]
The only ones I care about are:

    python setup.py install (used by pip install)
    python setup.py develop (used by pip install -e)

**Comment by nth10sd** [comment]
I have a working solution in my GitHub fork that needs a rebase after #48 goes through. This diff forces all files to use `absolute_import` from `__future__` and removes most of the `sys.path` hacks from the old legacy system.

To account for pip's directory sensitivities (yes, it's incredibly sensitive), I reorganised into the following structure that is slightly tweaked (either in name, e.g. using `src` instead over `core`, or otherwise) from our proposals above:

```
Most lithium code now sits in src/lithium, other than this change:

lithium/lithium.py ➡️ src/lithium/reducer.py
lithium/test_lithium.py ➡️ src/lithium/tests/test_lithium.py

interestingness/ ➡️ src/lithium/interestingness/

lithium/doc/ ➡️ src/lithium/docs/
lithium/examples/ ➡️ src/lithium/docs/examples/
lithium/examples/arithmetic/ ➡️ src/lithium/docs/examples/arithmetic/
```

`doc` got renamed to `docs` to ensure consistency with the `tests` folder.

`pip install` and `pip install -e` both work properly, but I feel we might want to have tests for these 2 usages later, as it was easy during development to break one particular usage instead of the other.

We should release 0.1 before landing this, due to the directory changes.
