### ISSUE TITLE
Move away from py.test in Travis .yml config

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/lithium#41]
We are using `py.test` in .travis.yml but not in .appveyor.yml - I thought it was the same as `pytest` or `python -m pytest` but apparently they are all different.

References:
* StackOverflow - pytest is the "[new hotness](https://stackoverflow.com/a/41893170)"
* pytest-dev #1629 - [Introduce pytest command as recommended entry point](https://github.com/pytest-dev/pytest/issues/1629)
  * "It's possible that in future we will deprecate py.test and potentially even remove it."
* pytest-dev #2564 - [calling pytest or python -m pytest should have identical behaviour](https://github.com/pytest-dev/pytest/issues/2564)

So it seems like we should at least move away from `py.test`. @jschwartzentruber what do you think it should be, `pytest` or `python -m pytest`?

**Comment by jschwartzentruber** [comment]
Standardizing on `python -m pytest`. @nth10sd will make a PR
