### ISSUE TITLE
Make chunk moving an option

### ISSUE THREAD

**Issue by nth10sd** [MozillaSecurity/lithium#54]
Currently, chunk moving is experimental, and [is prevented from running](https://github.com/MozillaSecurity/lithium/blob/f69ee760cae1c60a6e7590d847111f59d8ac9f81/src/lithium/reducer.py#L687) by a boolean statement. (not commented out to keep the linters running on it)

We could turn it into an option as a start, while still labelling it experimental.

**Comment by jschwartzentruber** [comment]
This was done at some point. `--strategy minimize-balanced --with-experimental-move`
