### ISSUE TITLE
problem to use lithium in windows

### ISSUE THREAD

**Issue by jplopezy** [MozillaSecurity/lithium#70]
Hi,

i'm trying use lithium on windows to reduce a testcase html crash of some app.

C:\Python27>python.exe -m lithium outputs --timeout=5 --timeout=120 "ASSERTION: index out of range"  C:\app.exe testcase.html
Intermediate files will be stored in tmp3\.
The original testcase has 822 lines.
Checking that the original testcase is 'interesting'...

The first error, which maybe I make is that I put "ASSERTION: index out of range", I do not understand that argument or that I should put according to the app or the file to be tested.

Currently the result is that the windbg is open with the crash and nothing else happens, except that it closes it by hand (the windbg) there ends the program.

Intermediate files will be stored in tmp3\.
The original testcase has 822 lines.
Checking that the original testcase is 'interesting'...
Exit status: TIMED OUT (409.658 seconds)
Lithium result: the original testcase is not 'interesting'!
  Tests performed: 1
  Test total: 822 lines

**Comment by nth10sd** [comment]
(nit: you have 2x --timeout parameters in your command)

You might want to also check that minidumps are being activated via this registry key:

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps
Name: DumpType  Type: REG_DWORD
```

See this [MSDN page](http://msdn.microsoft.com/en-us/library/windows/desktop/bb787181%28v=vs.85%29.aspx). That way, a dump should be generated instead of having windbg run.

**Comment by jschwartzentruber** [comment]
If you need further help with this, please ask in https://riot.im/app/#/room/#fuzzing:mozilla.org
