### ISSUE TITLE
crashes interestingness goes down useless path

### ISSUE THREAD

**Issue by kokanin** [MozillaSecurity/lithium#72]
I have an application with two crash paths, where one is interesting (for me) and the other not. When reducing the test case, I end up with a small file triggering the uninteresting part - any bright ideas on how to mark a specific crash type (stack overrun, div by 0 or similar) as not interesting without implementing a full debugger?

**Comment by nth10sd** [comment]
There is an interestingness test in the funfuzz repository called [crashesat](https://github.com/MozillaSecurity/funfuzz/blob/63c7e414071f0df091d5d69b19cf2afa7d98346e/src/funfuzz/util/crashesat.py) that allows you to mark a specific type of symptom as "interesting".

Perhaps you'd like to give that a try?

**Comment by kokanin** [comment]
this looks like it can be worked into something, thanks!
